apiVersion: batch/v1
kind: Job
metadata:
  name: {job_id}
spec:
  template:
    metadata:
      labels:
        app: benchmark-ai
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - benchmark-ai
            topologyKey: kubernetes.io/hostname
      containers:
      - name: {container_name}
        image: {docker_image}
        command: ["/bin/sh", "-c"]
        args:
          - {container_args}
        securityContext:
          privileged: {privileged}
      nodeSelector:
        beta.kubernetes.io/instance-type: {instance_type}
      restartPolicy: Never
  backoffLimit: 4
