name: metrics-pusher
channels:
  - conda-forge
  - defaults
dependencies:
  - python 3.7.*
  - elasticsearch 6.3.*
  - python-kubernetes 8.0.*
  - configargparse 0.14.*
  - kafka-python 1.4.*
  - pip
  - pip:
      - ConfigArgParse
      - dataclasses-json
      - dacite
