kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fetcher-dispatcher-it
  namespace: default
rules:
- apiGroups: ["","batch"]
  resources: ["pods", "jobs"]
  verbs: ["list","get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fetcher-dispatcher-it-status-binding
subjects:
- kind: ServiceAccount
  name: fetcher-dispatcher
  namespace: default
roleRef:
  kind: Role
  name: fetcher-dispatcher-it
  apiGroup: rbac.authorization.k8s.io