apiVersion: v1
kind: ConfigMap
data:
  consumer_group_id: fetcher-dispatcher
  consumer_topic: BAI_APP_FETCHER
  producer_topic: BAI_APP_EXECUTOR
  status_topic: BAI_APP_STATUS

  transpiler_puller_docker_image: benchmarkai/puller
  transpiler_metrics_pusher_docker_image: benchmarkai/metrics-pusher
  suppress_job_affinity: false
metadata:
  name: executor
  namespace: default