name: fetcher
channels:
  - conda-forge
  - defaults
dependencies:
  - python 3.7.*
  - kazoo 2.5.*
  - kafka-python 1.4.*
  - boto3 1.9.*
  - python-kubernetes 9.0.*
  - pycurl 7.43.*
  - pip
  - pip:
      - dataclasses-json
      - ConfigArgParse
      - dacite
