apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher-dispatcher
  labels:
    app: benchmark-ai
spec:
  selector:
   matchLabels:
      app: benchmark-ai
  replicas: 3
  template:
    metadata:
      labels:
        app: benchmark-ai
        service: fetcher-dispatcher
    spec:
      serviceAccountName: fetcher-dispatcher
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: service
                    operator: In
                    values:
                      - fetcher-dispatcher
              topologyKey: kubernetes.io/hostname
      containers:
        - name: fetcher-dispatcher
          image: stsukrov/fetcher-dispatcher
          env:
            - name: FETCHER_JOB_IMAGE
              value: stsukrov/datafetcher
            - name: S3_DATASET_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: outputs-infrastructure
                  key: data_pull_s3
            - name: ZOOKEEPER_ENSEMBLE_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: zookeeper
                  key: connect
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: outputs-infrastructure
                  key: msk_bootstrap_brokers
            - name: CONSUMER_GROUP_ID
              value: fetcher-dispatcher
            - name: CONSUMER_TOPIC
              value: BAI_APP_BFF
            - name: PRODUCER_TOPIC
              value: BAI_APP_FETCHER
            - name: LOGGING_LEVEL
              value: INFO
            - name: FETCHER_NODE_SELECTOR
              value: '{"node.type":"bai-services-network"}'
      nodeSelector:
        node.type: bai-services-cheap
      restartPolicy: Always
