name: sm-executor
channels:
  - conda-forge
  - defaults
dependencies:
  - python 3.7.*
  - addict 2.2.*
  - ConfigArgParse >= 0.13
  - python-crontab >= 2.3
  - flake8
  - kafka-python 1.4.6
  - boto3 1.9.*
  - pip
  - toml 0.9.*
  - pip:
    - dataclasses-json==0.2.7
    - dacite
    - sagemaker
    - tensorflow
    - pydevd-pycharm
