apiVersion: v1
kind: ServiceAccount
metadata:
  name: executor
---
# Role for creating jobs
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-execution
  namespace: default
rules:
- apiGroups: ["","batch"]
  resources: ["jobs"]
  verbs: ["create", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: executor-job-creation-binding
subjects:
- kind: ServiceAccount
  name: executor
  namespace: default
roleRef:
  kind: Role
  name: job-execution
  apiGroup: rbac.authorization.k8s.io
---
# Role for creating ConfigMaps
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: configmap-execution
  namespace: default
rules:
- apiGroups: ["","batch"]
  resources: ["configmaps"]
  verbs: ["create", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: executor-configmap-creation-binding
subjects:
- kind: ServiceAccount
  name: executor
  namespace: default
roleRef:
  kind: Role
  name: configmap-execution
  apiGroup: rbac.authorization.k8s.io
---
# Role for executing MPIJobs
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mpijob-execution
rules:
- apiGroups: ["","batch", "kubeflow.org"]
  resources: ["mpijobs"]
  verbs: ["create", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: executor-mpijob-creation-binding
  namespace:
subjects:
- kind: ServiceAccount
  name: executor
  namespace:
roleRef:
  kind: Role
  name: mpijob-execution
  apiGroup: rbac.authorization.k8s.io
