apiVersion: v1
kind: ServiceAccount
metadata:
  name: fetcher-dispatcher
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fetcher-dispatcher
  namespace: default
rules:
- apiGroups: ["","batch"]
  resources: ["jobs"]
  verbs: ["create", "deletecollection"]
- apiGroups: ["","batch"]
  resources: ["pods"]
  verbs: ["deletecollection"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fetcher-dispatcher-it
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "jobs"]
  verbs: ["list","get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fetcher-dispatcher-pod-status-binding
subjects:
- kind: ServiceAccount
  name: fetcher-dispatcher
  namespace: default
roleRef:
  kind: Role
  name: fetcher-dispatcher
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fetcher-dispatcher-it-status-binding
subjects:
- kind: ServiceAccount
  name: fetcher-dispatcher
  namespace: default
roleRef:
  kind: Role
  name: fetcher-dispatcher-it
  apiGroup: rbac.authorization.k8s.io
